# coding: utf-8

"""
    SaaSus Auth API Schema

    スキーマ

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

import openapi_client
from openapi_client.api.user_attribute_api import UserAttributeApi  # noqa: E501
from openapi_client.rest import ApiException


class TestUserAttributeApi(unittest.TestCase):
    """UserAttributeApi unit test stubs"""

    def setUp(self):
        self.api = openapi_client.api.user_attribute_api.UserAttributeApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_user_attribute(self):
        """Test case for create_user_attribute

        ユーザー属性の作成(Create User Attributes)  # noqa: E501
        """
        pass

    def test_delete_user_attribute(self):
        """Test case for delete_user_attribute

        ユーザー属性の削除(Delete User Attribute)  # noqa: E501
        """
        pass

    def test_get_user_attributes(self):
        """Test case for get_user_attributes

        ユーザー属性の一覧を取得(Get User Attributes)  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
