# coding: utf-8

"""
    SaaSus Auth API Schema

    スキーマ

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

import openapi_client
from openapi_client.models.tenants import Tenants  # noqa: E501
from openapi_client.rest import ApiException

class TestTenants(unittest.TestCase):
    """Tenants unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test Tenants
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Tenants`
        """
        model = openapi_client.models.tenants.Tenants()  # noqa: E501
        if include_optional :
            return Tenants(
                tenants = [
                    openapi_client.models.テナント情報(tenants).テナント情報(Tenants)()
                    ]
            )
        else :
            return Tenants(
                tenants = [
                    openapi_client.models.テナント情報(tenants).テナント情報(Tenants)()
                    ],
        )
        """

    def testTenants(self):
        """Test Tenants"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
