# coding: utf-8

"""
    SaaSus Auth API Schema

    スキーマ

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

import openapi_client
from openapi_client.models.authorization_temp_code import AuthorizationTempCode  # noqa: E501
from openapi_client.rest import ApiException

class TestAuthorizationTempCode(unittest.TestCase):
    """AuthorizationTempCode unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test AuthorizationTempCode
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AuthorizationTempCode`
        """
        model = openapi_client.models.authorization_temp_code.AuthorizationTempCode()  # noqa: E501
        if include_optional :
            return AuthorizationTempCode(
                code = '69e732d6-8ecc-45c4-c2eb-8438f7ffe775'
            )
        else :
            return AuthorizationTempCode(
                code = '69e732d6-8ecc-45c4-c2eb-8438f7ffe775',
        )
        """

    def testAuthorizationTempCode(self):
        """Test AuthorizationTempCode"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
