# coding: utf-8

"""
    SaaSus Auth API Schema

    スキーマ

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

import openapi_client
from openapi_client.models.update_customize_page_settings_param import UpdateCustomizePageSettingsParam  # noqa: E501
from openapi_client.rest import ApiException

class TestUpdateCustomizePageSettingsParam(unittest.TestCase):
    """UpdateCustomizePageSettingsParam unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test UpdateCustomizePageSettingsParam
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `UpdateCustomizePageSettingsParam`
        """
        model = openapi_client.models.update_customize_page_settings_param.UpdateCustomizePageSettingsParam()  # noqa: E501
        if include_optional :
            return UpdateCustomizePageSettingsParam(
                title = 'SaaSus', 
                terms_of_service_url = 'http://dev.example.com/terms', 
                privacy_policy_url = 'http://dev.example.com/privacy', 
                google_tag_manager_container_id = 'GTM-XXXXXXX', 
                icon = 'data:image/png;base64,ZDMiIHN0UmVmOmRvY3VtZW50SUQ9Inhtc==', 
                favicon = 'data:image/png;base64,ZDMiIHN0UmVmOmRvY3VtZW50SUQ9Inhtc=='
            )
        else :
            return UpdateCustomizePageSettingsParam(
                title = 'SaaSus',
                terms_of_service_url = 'http://dev.example.com/terms',
                privacy_policy_url = 'http://dev.example.com/privacy',
                google_tag_manager_container_id = 'GTM-XXXXXXX',
                icon = 'data:image/png;base64,ZDMiIHN0UmVmOmRvY3VtZW50SUQ9Inhtc==',
                favicon = 'data:image/png;base64,ZDMiIHN0UmVmOmRvY3VtZW50SUQ9Inhtc==',
        )
        """

    def testUpdateCustomizePageSettingsParam(self):
        """Test UpdateCustomizePageSettingsParam"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
