# coding: utf-8

"""
    SaaSus Auth API Schema

    スキーマ

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

import openapi_client
from openapi_client.api.error_api import ErrorApi  # noqa: E501
from openapi_client.rest import ApiException


class TestErrorApi(unittest.TestCase):
    """ErrorApi unit test stubs"""

    def setUp(self):
        self.api = openapi_client.api.error_api.ErrorApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_return_internal_server_error(self):
        """Test case for return_internal_server_error

        ステータスコード500でサーバーエラーを返却(Return Internal Server Error)  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
