# coding: utf-8

"""
    SaaSus Auth API Schema

    スキーマ

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

import openapi_client
from openapi_client.api.tenant_user_api import TenantUserApi  # noqa: E501
from openapi_client.rest import ApiException


class TestTenantUserApi(unittest.TestCase):
    """TenantUserApi unit test stubs"""

    def setUp(self):
        self.api = openapi_client.api.tenant_user_api.TenantUserApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_tenant_user(self):
        """Test case for create_tenant_user

        テナントにユーザーを作成(Create Tenant User)  # noqa: E501
        """
        pass

    def test_create_tenant_user_roles(self):
        """Test case for create_tenant_user_roles

        テナントのユーザー情報に役割(ロール)を作成(Create Tenant User Role)  # noqa: E501
        """
        pass

    def test_delete_tenant_user(self):
        """Test case for delete_tenant_user

        テナントのユーザー情報を削除(Delete Tenant User)  # noqa: E501
        """
        pass

    def test_delete_tenant_user_role(self):
        """Test case for delete_tenant_user_role

        テナントのユーザーから役割(ロール)を削除(Remove Role From Tenant User)  # noqa: E501
        """
        pass

    def test_get_all_tenant_user(self):
        """Test case for get_all_tenant_user

        ユーザー情報を取得(Get User Info)  # noqa: E501
        """
        pass

    def test_get_all_tenant_users(self):
        """Test case for get_all_tenant_users

        ユーザー一覧を取得(Get Users)  # noqa: E501
        """
        pass

    def test_get_tenant_user(self):
        """Test case for get_tenant_user

        テナントのユーザー情報を取得(Get Tenant User)  # noqa: E501
        """
        pass

    def test_get_tenant_users(self):
        """Test case for get_tenant_users

        テナントのユーザー一覧を取得(Get Tenant Users)  # noqa: E501
        """
        pass

    def test_update_tenant_user(self):
        """Test case for update_tenant_user

        テナントのユーザー属性情報を更新(Update Tenant User Attribute)  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
