# coding: utf-8

"""
    SaaSus Auth API Schema

    スキーマ

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

import openapi_client
from openapi_client.api.role_api import RoleApi  # noqa: E501
from openapi_client.rest import ApiException


class TestRoleApi(unittest.TestCase):
    """RoleApi unit test stubs"""

    def setUp(self):
        self.api = openapi_client.api.role_api.RoleApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_role(self):
        """Test case for create_role

        役割(ロール)を作成(Create Role)  # noqa: E501
        """
        pass

    def test_delete_role(self):
        """Test case for delete_role

        役割(ロール)を削除(Delete Role)  # noqa: E501
        """
        pass

    def test_get_roles(self):
        """Test case for get_roles

        役割(ロール)一覧を取得(Get Roles)  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
