# coding: utf-8

"""
    SaaSus Auth API Schema

    スキーマ

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

import openapi_client
from openapi_client.models.provider_name import ProviderName  # noqa: E501
from openapi_client.rest import ApiException

class TestProviderName(unittest.TestCase):
    """ProviderName unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testProviderName(self):
        """Test ProviderName"""
        # inst = ProviderName()

if __name__ == '__main__':
    unittest.main()
