# coding: utf-8

"""
    SaaSus Pricing API Schema

    SaaSus Pricing API Schema

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json



from pydantic import ConfigDict, BaseModel, Field, StrictStr

class UpdateTaxRateParam(BaseModel):
    """
    UpdateTaxRateParam
    """
    display_name: StrictStr = Field(..., description="Display name")
    description: StrictStr = Field(..., description="Description")
    __properties = ["display_name", "description"]
    model_config = ConfigDict(populate_by_name=True, validate_assignment=True)

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> UpdateTaxRateParam:
        """Create an instance of UpdateTaxRateParam from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> UpdateTaxRateParam:
        """Create an instance of UpdateTaxRateParam from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return UpdateTaxRateParam.parse_obj(obj)

        _obj = UpdateTaxRateParam.parse_obj({
            "display_name": obj.get("display_name"),
            "description": obj.get("description")
        })
        return _obj


