# coding: utf-8

"""
    SaaSus AWS Marketplace API Schema

    SaaSus AWS Marketplace API Schema

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import json
import pprint
import re  # noqa: F401
from aenum import Enum, no_arg





class ListingStatus(str, Enum):
    """
    ListingStatus
    """

    """
    allowed enum values
    """
    NO_LISTING = 'no_listing'
    FIRST_STEP_WORKING = 'first_step_working'
    FIRST_STEP_COMPLETED = 'first_step_completed'
    SECOND_STEP_WORKING = 'second_step_working'
    SECOND_STEP_PLAN_CREATED = 'second_step_plan_created'
    SECOND_STEP_COMPLETED = 'second_step_completed'
    THIRD_STEP_WORKING = 'third_step_working'
    THIRD_STEP_COMPLETED = 'third_step_completed'
    LIMITED = 'limited'
    RESTRICTED = 'restricted'
    PUBLIC = 'public'

    @classmethod
    def from_json(cls, json_str: str) -> ListingStatus:
        """Create an instance of ListingStatus from a JSON string"""
        return ListingStatus(json.loads(json_str))


