# coding: utf-8

"""
    SaaSus AWS Marketplace API Schema

    SaaSus AWS Marketplace API Schema

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import json
import pprint
import re  # noqa: F401
from aenum import Enum, no_arg





class VisibilityStatus(str, Enum):
    """
    VisibilityStatus
    """

    """
    allowed enum values
    """
    PUBLIC = 'Public'
    LIMITED = 'Limited'
    RESTRICTED = 'Restricted'

    @classmethod
    def from_json(cls, json_str: str) -> VisibilityStatus:
        """Create an instance of VisibilityStatus from a JSON string"""
        return VisibilityStatus(json.loads(json_str))


