# coding: utf-8

"""
    SaaSus Eventbridge API Schema

    SaaSus Eventbridge API Schema

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import List
from pydantic import ConfigDict, BaseModel, Field
from saasus_sdk_python.src.integration.models.event_message import EventMessage
from typing_extensions import Annotated

class CreateEventBridgeEventParam(BaseModel):
    """
    CreateEventBridgeEventParam
    """
    event_messages: Annotated[List[EventMessage], Field()] = Field(..., description="event message")
    __properties = ["event_messages"]
    model_config = ConfigDict(populate_by_name=True, validate_assignment=True)

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> CreateEventBridgeEventParam:
        """Create an instance of CreateEventBridgeEventParam from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        # override the default output from pydantic by calling `to_dict()` of each item in event_messages (list)
        _items = []
        if self.event_messages:
            for _item in self.event_messages:
                if _item:
                    _items.append(_item.to_dict())
            _dict['event_messages'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> CreateEventBridgeEventParam:
        """Create an instance of CreateEventBridgeEventParam from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return CreateEventBridgeEventParam.parse_obj(obj)

        _obj = CreateEventBridgeEventParam.parse_obj({
            "event_messages": [EventMessage.from_dict(_item) for _item in obj.get("event_messages")] if obj.get("event_messages") is not None else None
        })
        return _obj


