# coding: utf-8

"""
    SaaSus Auth API Schema

    Schema

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import Optional
from pydantic import BaseModel, Field, StrictStr

class DeviceSecretVerifierConfig(BaseModel):
    """
    The configuration of the device secret verifier. 
    """
    password_verifier: Optional[StrictStr] = Field(None, description="A password verifier for a user's device. Used in SRP authentication.")
    salt: Optional[StrictStr] = Field(None, description="The salt for SRP authentication with the user's device.")
    __properties = ["password_verifier", "salt"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> DeviceSecretVerifierConfig:
        """Create an instance of DeviceSecretVerifierConfig from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> DeviceSecretVerifierConfig:
        """Create an instance of DeviceSecretVerifierConfig from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return DeviceSecretVerifierConfig.parse_obj(obj)

        _obj = DeviceSecretVerifierConfig.parse_obj({
            "password_verifier": obj.get("password_verifier"),
            "salt": obj.get("salt")
        })
        return _obj


