# coding: utf-8

"""
    SaaSus Auth API Schema

    Schema

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json



from pydantic import BaseModel, Field, StrictInt
from saasus_sdk_python.src.auth.models.refresh_token_validity_unit import RefreshTokenValidityUnit

class RefreshTokenValidity(BaseModel):
    """
    Refresh token validity period.
    """
    value: StrictInt = Field(..., description="Refresh token validity value. The duration must be between 60 minutes and 10 years. ")
    unit: RefreshTokenValidityUnit = Field(...)
    __properties = ["value", "unit"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> RefreshTokenValidity:
        """Create an instance of RefreshTokenValidity from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> RefreshTokenValidity:
        """Create an instance of RefreshTokenValidity from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return RefreshTokenValidity.parse_obj(obj)

        _obj = RefreshTokenValidity.parse_obj({
            "value": obj.get("value"),
            "unit": obj.get("unit")
        })
        return _obj


