# coding: utf-8

"""
    SaaSus Auth API Schema

    Schema

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import Any, Dict
from pydantic import ConfigDict, BaseModel, Field, StrictStr

class TenantProps(BaseModel):
    """
    TenantProps
    """
    name: StrictStr = Field(..., description="tenant name")
    attributes: Dict[str, Any] = Field(..., description="attribute info")
    back_office_staff_email: StrictStr = Field(..., description="administrative staff email address")
    __properties = ["name", "attributes", "back_office_staff_email"]
    model_config = ConfigDict(populate_by_name=True, validate_assignment=True)

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> TenantProps:
        """Create an instance of TenantProps from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> TenantProps:
        """Create an instance of TenantProps from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return TenantProps.parse_obj(obj)

        _obj = TenantProps.parse_obj({
            "name": obj.get("name"),
            "attributes": obj.get("attributes"),
            "back_office_staff_email": obj.get("back_office_staff_email")
        })
        return _obj


