# coding: utf-8

"""
    SaaSus Pricing API Schema

    SaaSus Pricing API Schema

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import json
import pprint
import re  # noqa: F401
from aenum import Enum, no_arg





class AggregateUsage(str, Enum):
    """
    使用量の集計方法(aggregate usage) sum: 期間内の使用量の合計(total usage during the period) max: 期間内の使用量の最大値(maximum usage during the period) 
    """

    """
    allowed enum values
    """
    SUM = 'sum'
    MAX = 'max'

    @classmethod
    def from_json(cls, json_str: str) -> AggregateUsage:
        """Create an instance of AggregateUsage from a JSON string"""
        return AggregateUsage(json.loads(json_str))


