# coding: utf-8

"""
    SaaSus Pricing API Schema

    SaaSus Pricing API Schema

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
import pprint
import re  # noqa: F401
from enum import Enum



try:
    from typing import Self
except ImportError:
    from typing_extensions import Self


class UnitType(str, Enum):
    """
    Unit of measurement type fixed: Fixed unit usage: Usage unit tiered: Tiered unit tiered_usage: Tiered usage unit 
    """

    """
    allowed enum values
    """
    FIXED = 'fixed'
    USAGE = 'usage'
    TIERED = 'tiered'
    TIERED_USAGE = 'tiered_usage'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of UnitType from a JSON string"""
        return cls(json.loads(json_str))


