# coding: utf-8

"""
    SaaSus Auth API Schema

    スキーマ

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json



from pydantic import BaseModel, Field, StrictBool, StrictStr

class CustomizePageProps(BaseModel):
    """
    CustomizePageProps
    """
    html_contents: StrictStr = Field(..., description="画面のHTMLを編集できます ※ 未提供の機能のため、変更・保存はできません  Edit page HTML ※ This function is not yet provided, so it cannot be changed or saved. ")
    is_terms_of_service: StrictBool = Field(..., description="利用規約の同意チェックボックスを表示するが設定されているか(display the terms of use agreement check box)")
    is_privacy_policy: StrictBool = Field(..., description="プライバシーポリシーチェックボックスを表示するが設定されているか(show the privacy policy checkbox)")
    __properties = ["html_contents", "is_terms_of_service", "is_privacy_policy"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> CustomizePageProps:
        """Create an instance of CustomizePageProps from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> CustomizePageProps:
        """Create an instance of CustomizePageProps from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return CustomizePageProps.parse_obj(obj)

        _obj = CustomizePageProps.parse_obj({
            "html_contents": obj.get("html_contents"),
            "is_terms_of_service": obj.get("is_terms_of_service"),
            "is_privacy_policy": obj.get("is_privacy_policy")
        })
        return _obj


