# coding: utf-8

"""
    SaaSus Auth API Schema

    Schema

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json



from pydantic import BaseModel, Field, StrictInt, StrictStr

class TenantUserCount(BaseModel):
    """
    TenantUserCount
    """
    tenant_id: StrictStr = Field(...)
    count: StrictInt = Field(..., description="Count of tenant users")
    updated_at: StrictInt = Field(..., description="Unix timestamp (seconds) of the last update")
    __properties = ["tenant_id", "count", "updated_at"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> TenantUserCount:
        """Create an instance of TenantUserCount from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> TenantUserCount:
        """Create an instance of TenantUserCount from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return TenantUserCount.parse_obj(obj)

        _obj = TenantUserCount.parse_obj({
            "tenant_id": obj.get("tenant_id"),
            "count": obj.get("count"),
            "updated_at": obj.get("updated_at")
        })
        return _obj


