# coding: utf-8

"""
    SaaSus Auth API Schema

    Schema

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import Optional
from pydantic import ConfigDict, BaseModel, Field, StrictStr

class UpdateEnvParam(BaseModel):
    """
    UpdateEnvParam
    """
    name: StrictStr = Field(..., description="env name")
    display_name: Optional[StrictStr] = Field(None, description="env display name")
    __properties = ["name", "display_name"]
    model_config = ConfigDict(populate_by_name=True, validate_assignment=True)

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> UpdateEnvParam:
        """Create an instance of UpdateEnvParam from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> UpdateEnvParam:
        """Create an instance of UpdateEnvParam from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return UpdateEnvParam.parse_obj(obj)

        _obj = UpdateEnvParam.parse_obj({
            "name": obj.get("name"),
            "display_name": obj.get("display_name")
        })
        return _obj


