name: Test Publish SaaSus SDK to TestPyPI

on:
  # 手動実行専用ワークフロー（本番と分離）
  workflow_dispatch:

jobs:
  test-publish:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: ["3.12"]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Python 環境のセットアップ
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      # Poetry 1.8.3 のインストール（バージョン固定）
      - name: Install Poetry
        run: |
          python -m pip install --upgrade pip
          pip install poetry==1.8.3

      # 依存関係を本番環境向けに最適化
      - name: Install Production Dependencies
        run: poetry install --no-dev

      # pyproject.toml のバージョンに `.dev+timestamp` を追加（TestPyPI 用に毎回ユニークなバージョンを作成
      - name: Bump version with timestamp
        run: |
          BASE_VERSION=$(poetry version -s)
          VERSION="${BASE_VERSION}.dev$(date +'%Y%m%d%H%M%S')"
          echo "Set version to $VERSION"
          poetry version "$VERSION"

      # パッケージのビルド
      - name: Build Package
        run: poetry build

      # TestPyPI をリポジトリとして登録（Poetry は本番以外は明示的登録が必要）
      - name: Configure TestPyPI repository
        run: poetry config repositories.testpypi https://test.pypi.org/legacy/

      # TestPyPI に公開
      - name: Publish to TestPyPI
        env:
          TEST_PYPI_API_TOKEN: ${{ secrets.TEST_PYPI_API_TOKEN }}
        run: poetry publish -r testpypi --username __token__ --password $TEST_PYPI_API_TOKEN
